export const adress_pull = [
  {
    id: "0",
    street: "Третья улица",
    house_number: "5",
    apartment_number: "210",
    electricity_spent: "142",
    water_cubes: "5",
    data: "07.09.2013",
  },
  {
    id: "1",
    street: "Дмитриевского улица",
    house_number: "2А",
    apartment_number: "11",
    electricity_spent: "124",
    water_cubes: "1",
    data: "07.10.2015",
  },
  {
    id: "2",
    street: "Викторенко улица",
    house_number: "3",
    apartment_number: "19",
    electricity_spent: "142",
    water_cubes: "3",
    data: "21.11.2021",
  },
  {
    id: "3",
    street: "Бутырская улица",
    house_number: "31",
    apartment_number: "26",
    electricity_spent: "230",
    water_cubes: "3",
    data: "27.10.2051",
  },
  {
    id: "4",
    street: "Козицкий улица",
    house_number: "9",
    apartment_number: "45",
    electricity_spent: "320",
    water_cubes: "6",
    data: "17.03.3013",
  },
  {
    id: "5",
    street: "Лесной улица",
    house_number: "6",
    apartment_number: "66",
    electricity_spent: "217",
    water_cubes: "2",
    data: "16.01.1973",
  },
  {
    id: "6",
    street: "Красногвардейский улица",
    house_number: "12",
    apartment_number: "122",
    electricity_spent: "521",
    water_cubes: "3",
    data: "14.13.2016",
  },
  {
    id: "7",
    street: "Лосевская улица",
    house_number: "1",
    apartment_number: "1",
    electricity_spent: "561",
    water_cubes: "1",
    data: "13.05.2020",
  },
  {
    id: "8",
    street: "Ковров улица",
    house_number: "10",
    apartment_number: "121",
    electricity_spent: "416",
    water_cubes: "5",
    data: "13.05.2009",
  },
  {
    id: "9",
    street: "Кантемировская улица",
    house_number: "7",
    apartment_number: "720",
    electricity_spent: "412",
    water_cubes: "6",
    data: "12.10.2007",
  },
  {
    id: "10",
    street: "Еланского улица",
    house_number: "1А",
    apartment_number: "22",
    electricity_spent: "314",
    water_cubes: "8",
    data: "07.12.2013",
  },
  {
    id: "11",
    street: "Площадь Европы",
    house_number: "1",
    apartment_number: "2",
    electricity_spent: "412",
    water_cubes: "9",
    data: "25.10.2008",
  },
  {
    id: "12",
    street: "Доватора улица",
    house_number: "4Б",
    apartment_number: "99",
    electricity_spent: "421",
    water_cubes: "5",
    data: "27.10.2013",
  },
  {
    id: "13",
    street: "Джанкойская улица",
    house_number: "1А",
    apartment_number: "111",
    electricity_spent: "432",
    water_cubes: "4",
    data: "01.01.2011",
  },
  {
    id: "14",
    street: "Гольяновская улица",
    house_number: "1Б",
    apartment_number: "10",
    electricity_spent: "523",
    water_cubes: "2",
    data: "02.05.1991",
  },
  {
    id: "15",
    street: "Гвоздева",
    house_number: "10",
    apartment_number: "78",
    electricity_spent: "234",
    water_cubes: "1",
    data: "03.02.2013",
  },
  {
    id: "16",
    street: "Газетный переулок",
    house_number: "3А",
    apartment_number: "70",
    electricity_spent: "125",
    water_cubes: "6",
    data: "21.06.2013",
  },
  {
    id: "17",
    street: "Гаврикова улица",
    house_number: "1Б",
    apartment_number: "84",
    electricity_spent: "412",
    water_cubes: "4",
    data: "22.04.2006",
  },
  {
    id: "18",
    street: "Гостиничная улица",
    house_number: "4",
    apartment_number: "154",
    electricity_spent: "324",
    water_cubes: "10",
    data: "11.03.2004",
  },
  {
    id: "19",
    street: "Гжатская улица",
    house_number: "1",
    apartment_number: "4",
    electricity_spent: "471",
    water_cubes: "5",
    data: "13.01.2011",
  },
  {
    id: "20",
    street: "Веселая улица",
    house_number: "12",
    apartment_number: "3",
    electricity_spent: "411",
    water_cubes: "7",
    data: "14.02.2010",
  },
];
